name: Typecheck and Unit Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  ci-check:
    name: Typecheck and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Typecheck
        run: yarn typecheck
      - name: Unit Tests
        run: yarn test
